language: node_js
node_js:
  - "0.10"
before_script:
    - "npm install -g jasmine-node@1.14.2 -g"
    - "npm install -g grunt-cli"
    - "grunt build"
    - "sleep 15"
services:
    - mongodb
before_install:
    - "while [ $(netstat -tnl | grep -c 27017) == 0 ]; do sleep 1; done"
    - "mongo --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true})' admin"
