language: node_js
node_js:
  - "0.10"
before_script:
    - "npm install -g jasmine-node"
    - "npm install -g grunt-cli"
    - "grunt build"
    - "sleep 15"
    - "mongod --setParameter textSearchEnabled=true"
services:
    - mongodb
before_install:
    - "mongo --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true})' admin"
